CREATE TABLE `LIFECYCLE_TABLES` (
	`DGNSS_DBMS_ID` CHAR(4) NOT NULL COMMENT '진단대상데이터베이스순번',
	`INSTT_CODE` CHAR(7) NOT NULL COMMENT '기관 코드',
	`DGNSS_INFO_ID` VARCHAR(20) NOT NULL COMMENT '진단 정보 아이디',
	`DGNSS_NM` VARCHAR(80) NULL DEFAULT NULL COMMENT '진단 명',
	`TABLE_NM` VARCHAR(80) NULL DEFAULT NULL COMMENT '테이블 명',
	`ALL_CO` INT(11) NULL DEFAULT NULL COMMENT '데이터 건수',
	`EXC_BEGIN_TIME` DATETIME NULL DEFAULT NULL COMMENT '수행 시작 시간',
	`EXC_END_TIME` DATETIME NULL DEFAULT NULL COMMENT '수행 종료 시간',
	`EXC_STTUS` CHAR(1) NULL DEFAULT NULL COMMENT '수행 상태',
	`REGIST_DT` DATETIME NULL DEFAULT NULL COMMENT '등록 일시',
	PRIMARY KEY (`DGNSS_DBMS_ID`, `INSTT_CODE`, `DGNSS_INFO_ID`),
	INDEX `FK_USER_TO_LIFECYCLE_TABLES` (`INSTT_CODE`),
	CONSTRAINT `FK_DGNSS_DBMS_TO_LIFECYCLE_TABLES` FOREIGN KEY (`DGNSS_DBMS_ID`, `INSTT_CODE`) REFERENCES `dgnss_dbms` (`DGNSS_DBMS_ID`, `INSTT_CODE`),
	CONSTRAINT `FK_USER_TO_LIFECYCLE_TABLES` FOREIGN KEY (`INSTT_CODE`) REFERENCES `user` (`INSTT_CODE`)
)
COMMENT='라이프사이클  진단 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;







CREATE TABLE `LIFECYCLE_ANALS` (
	`INSTT_CODE` CHAR(7) NOT NULL COMMENT '기관 코드',
	`ANALS_ID` CHAR(4) NOT NULL COMMENT '분석 순번',
	`ANALS_SE` VARCHAR(20) NULL DEFAULT NULL COMMENT '분석 구분',
	`ANALS_TY` VARCHAR(20) NULL DEFAULT NULL COMMENT '분석 타입',
	`PTTRN_SE` VARCHAR(20) NULL DEFAULT NULL COMMENT '패턴 구분',
    `FIELD_NM` VARCHAR(20) NULL DEFAULT NULL COMMENT '항목명',
    `PERIOD_CL` VARCHAR(5) NULL DEFAULT NULL COMMENT '기간 구분',
    `PERIOD` INT(4) NULL DEFAULT NULL COMMENT '기간',
	`RM` TEXT NULL COMMENT '비고',
	`USE_AT` BIT(1) NULL DEFAULT NULL COMMENT '사용 여부',
	`REGIST_DT` DATETIME NULL DEFAULT NULL COMMENT '등록 일시',
	PRIMARY KEY (`INSTT_CODE`, `ANALS_ID`)
)
COMMENT='라이프사이클 분석 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;




CREATE TABLE `LIFECYCLE_TABLES_RES` (
	`INSTT_CODE` CHAR(7) NOT NULL COMMENT '기관 코드',
	`DGNSS_DBMS_ID` CHAR(4) NOT NULL COMMENT '진단대상데이터베이스순번',
	`DGNSS_INFO_ID` VARCHAR(20) NOT NULL COMMENT '진단 정보 아이디',
	`TABLE_NM` VARCHAR(80) NOT NULL COMMENT '테이블 명',
	`ANALS_ID` CHAR(4) NOT NULL COMMENT '분석 순번',
	`MTCHG_CO` INT(11) NULL DEFAULT NULL COMMENT '매칭 건수',
    `MISS_CO` INT(11) NULL DEFAULT NULL COMMENT '초과 건수',
	`REGIST_DT` DATETIME NULL DEFAULT NULL COMMENT '등록 일시',
	PRIMARY KEY (`INSTT_CODE`, `DGNSS_DBMS_ID`, `DGNSS_INFO_ID`, `TABLE_NM`, `ANALS_ID`),
	INDEX `FK_LIFECYCLE_ANALS_TO_LIFECYCLE_TABLES_RES` (`INSTT_CODE`, `ANALS_ID`),
	CONSTRAINT `FK_LIFECYCLE_ANALS_TO_LIFECYCLE_TABLES_RES` FOREIGN KEY (`INSTT_CODE`, `ANALS_ID`) REFERENCES `LIFECYCLE_ANALS` (`INSTT_CODE`, `ANALS_ID`),
	CONSTRAINT `FK_LIFECYCLE_TABLES_TO_LIFECYCLE_TABLES_RES` FOREIGN KEY (`INSTT_CODE`, `DGNSS_DBMS_ID`, `DGNSS_INFO_ID`) REFERENCES `LIFECYCLE_TABLES` (`INSTT_CODE`, `DGNSS_DBMS_ID`, `DGNSS_INFO_ID`)
)
COMMENT='테이블별 진단 항목별 진단 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;









CREATE TABLE `LIFECYCLE_TABLES_ERROR` (
	`INSTT_CODE` CHAR(7) NOT NULL COMMENT '기관 코드',
	`DGNSS_DBMS_ID` CHAR(4) NOT NULL COMMENT '진단대상데이터베이스순번',
	`DGNSS_INFO_ID` VARCHAR(20) NOT NULL COMMENT '진단 정보 아이디',
	`COLUMN_NM` VARCHAR(80) NULL DEFAULT NULL COMMENT '컬럼 명',
	`ANALS_ID` CHAR(4) NULL DEFAULT NULL COMMENT '분석 아이디',
	`DGNSS_ERROR_ID` VARCHAR(20) NOT NULL COMMENT '진단오류 아이디',
	`SCHEMA_NM` VARCHAR(50) NULL DEFAULT NULL COMMENT '스키마 명',
	`TABLE_NM` VARCHAR(80) NULL DEFAULT NULL COMMENT '테이블 명',
	`ERROR_NM` TEXT NULL COMMENT '오류 명',
	`ERROR_CONTENT` TEXT NULL COMMENT '오류 내용',
	`REGIST_DT` DATETIME NULL DEFAULT NULL COMMENT '등록 일시',
	PRIMARY KEY (`DGNSS_ERROR_ID`),
	INDEX `FK_LIFECYCLE_TABLES_TO_LIFECYCLE_TABLES_ERROR` (`INSTT_CODE`, `DGNSS_DBMS_ID`, `DGNSS_INFO_ID`),
	CONSTRAINT `FK_LIFECYCLE_TABLES_TO_LIFECYCLE_TABLES_ERROR` FOREIGN KEY (`INSTT_CODE`, `DGNSS_DBMS_ID`, `DGNSS_INFO_ID`) REFERENCES `LIFECYCLE_TABLES` (`INSTT_CODE`, `DGNSS_DBMS_ID`, `DGNSS_INFO_ID`)
)
COMMENT='라이프사이클 오류 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

