-- 이용자 권한
CREATE TABLE `AUTHORITY` (
	`USER_ID`    VARCHAR(255) NOT NULL COMMENT '이용자 ID', -- 이용자 ID
	`AUTHOR_CODE` VARCHAR(255) NULL COMMENT '권한 코드' -- 권한 코드
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '이용자권한';

-- 이용자권한
ALTER TABLE `AUTHORITY`
	ADD CONSTRAINT `PK_AUTHORITY` -- 이용자권한 기본키
		PRIMARY KEY (
			`USER_ID` -- 이용자 ID
		);
		
-- 이용자 권한 데이터
INSERT INTO `AUTHORITY` (`USER_ID`,`AUTHOR_CODE`) VALUES ('admin','ROLE_ADMIN');




-- 이용자
CREATE TABLE `USER` (
	`INSTT_CODE`        VARCHAR(20)  NOT NULL COMMENT '기관코드', -- 기관코드
	`USER_ID`          VARCHAR(255) NOT NULL COMMENT '이용자 ID', -- 이용자 ID
	-- [삭제] `AUTHOR_CODE`      VARCHAR(20)  NOT NULL COMMENT '권한 코드', -- 권한 코드
	`USER_PASSWORD`    VARCHAR(255) NOT NULL COMMENT '이용자 비밀번호', -- 이용자 비밀번호
	`USER_NM`          VARCHAR(255) NULL     COMMENT '이용자 이름', -- 이용자 이름
	`CHRG_DEPT`        VARCHAR(255) NULL     COMMENT '담당부서', -- 담당부서
	`RECENT_CONECT_DT` DATE         NULL     COMMENT '최근접속일시', -- 최근접속일시
	`RECENT_CONECT_IP` VARCHAR(255) NULL     COMMENT '최근접속아이피', -- 최근접속아이피
	`RM`               VARCHAR(255) NULL     COMMENT '비고', -- 비고
	`USE_AT`           VARCHAR(1)   NULL     COMMENT '사용여부' -- 사용여부
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '이용자';

-- 이용자
ALTER TABLE `USER`
	ADD CONSTRAINT `PK_USER` -- 이용자 기본키
		PRIMARY KEY (
			`INSTT_CODE`,     -- 기관코드
			`USER_ID`       	-- 이용자 ID
			-- [삭제] `AUTHOR_CODE`,   -- 권한 코드
		);

-- 이용자
ALTER TABLE `USER`
	ADD CONSTRAINT `FK_AUTHORITY_TO_USER` -- 이용자권한 -> 이용자
		FOREIGN KEY (
			`USER_ID` -- 이용자 ID
		)
		REFERENCES `AUTHORITY` ( -- 이용자권한
			`USER_ID` -- 이용자 ID
		);
		
		
-- 이용자 데이터
INSERT INTO `USER` (`INSTT_CODE`,`USER_ID`,`USER_PASSWORD`,`USER_NM`,`CHRG_DEPT`,`RECENT_CONECT_DT`,`RECENT_CONECT_IP`,`RM`,`USE_AT`) VALUES ('1075150','admin','$2a$10$GdDOHJ/2Dd6jJ7jZ0DaB9OvS6pdpIWFn3rSJBB6GjFoL8uyjkycuq','관리자','부마민주항쟁진상규명및관련자명예회복심의위원회','2019-06-20','0:0:0:0:0:0:0:1','','Y');










-- 기관 관리
CREATE TABLE `INSTT_MANAGE` (
	`INSTT_CODE`        VARCHAR(20)  NOT NULL, -- 기관 코드
	`INSTT_NM`          VARCHAR(255) NULL,     -- 기관 명
	`LWPRT_INSTT_NM`    VARCHAR(255) NULL,     -- 하위기관 명
	`ODR`               INT(11)      NULL,     -- 차수
	`ORD`               INT(11)      NULL,     -- 서열
	`PSTINST_ODR`       INT(11)      NULL,     -- 소속기관 차수
	`SEHIGH_INSTT_CODE` VARCHAR(20)  NULL,     -- 차상위 기관 코드
	`BEST_INSTT_CODE`   VARCHAR(20)  NULL,     -- 최상위 기관 코드
	`REPRSNT_INSTT_CODE`VARCHAR(20)  NULL,     -- 대표 기관 코드
	`TY_CL_LRGE`        INT(11)      NULL,     -- 유형분류 대
	`TY_CL_MIDDL`       INT(11)      NULL,     -- 유형분류 중
	`TY_CL_SMALL`       INT(11)      NULL,     -- 유형분류 소
	`ZIP`               INTEGER      NULL,     -- 우편번호
	`LNM`               INTEGER      NULL,     -- 지번
	`ADRES`             VARCHAR(255) NULL,     -- 주소
	`TELNO`             VARCHAR(127) NULL,     -- 전화번호
	`FXNUM`             VARCHAR(127) NULL      -- 팩스번호
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '기관 관리';

-- 기관 관리
ALTER TABLE `INSTT_MANAGE`
	ADD CONSTRAINT `PK_INSTT_MANAGE` -- 기관관리 기본키
		PRIMARY KEY (
			`INSTT_CODE` -- 기관 코드
		);
		
-- 기관 관리 데이터
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('1075150','부마민주항쟁진상규명및관련자명예회복심의위원회','부마민주항쟁진상규명및관련자명예회복심의위원회',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('111111','TEST1','테스트1',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('222222','TEST2','테스트2',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('333333','TEST3','테스트3',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('444444','TEST4','테스트4',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('555555','TEST5','테스트5',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('666666','TEST6','테스트6',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('777777','TEST7','테스트7',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('888888','TEST8','테스트8',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('999999','TEST9','테스트9',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');
INSERT INTO `INSTT_MANAGE` (`INSTT_CODE`,`INSTT_NM`,`LWPRT_INSTT_NM`,`ODR`,`ORD`,`PSITN_INSTT_ODR`,`SEHIGH_INSTT_CODE`,`BEST_INSTT_CODE`,`REPRSNT_INSTT_CODE`,`TY_CL_LRGE`,`TY_CL_MIDDL`,`TY_CL_SMALL`,`ZIP`,`LNM`,`ADRES`,`TELNO`,`FXNUM`) VALUES ('999999','TEST9','테스트9',1,79,0,'0','1075150','1075150',1,1,7,3044,350034,'코오롱빌딩 3층','02-6744-3116','02-6744-3199');		
	









-- 공통코드
CREATE TABLE `CMMN_CODE` (
	`GROUP_CODE`    VARCHAR(300)  NOT NULL COMMENT '그룹 코드', -- 그룹 코드
	`GROUP_CODE_NM` VARCHAR(300)  NULL     COMMENT '그룹 코드 명', -- 그룹 코드 명
	`GROUP_CODE_DC` VARCHAR(2048) NULL     COMMENT '그룹 코드 설명', -- 그룹 코드 설명
	`USE_AT`        VARCHAR(1)    NULL     COMMENT '사용 여부' -- 사용 여부
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '공통코드';

-- 공통코드
ALTER TABLE `CMMN_CODE`
	ADD CONSTRAINT `PK_CMMN_CODE` -- 공통코드 기본키
		PRIMARY KEY (
			`GROUP_CODE` -- 그룹 코드
		);
		
-- 공통코드 데이터
INSERT INTO `CMMN_CODE` (`GROUP_CODE`,`GROUP_CODE_NM`,`GROUP_CODE_DC`,`USE_AT`) VALUES ('DQ_CODE','그룹코드',NULL,'Y');
INSERT INTO `CMMN_CODE` (`GROUP_CODE`,`GROUP_CODE_NM`,`GROUP_CODE_DC`,`USE_AT`) VALUES ('DQ_CODE_A','그룹코드',NULL,'Y');		








		
-- 공통코드상세
CREATE TABLE `CMMN_CODE_DETAIL` (
	`GROUP_CODE`      VARCHAR(300)  NOT NULL COMMENT '그룹 코드', -- 그룹 코드
	`CMMN_CODE`       VARCHAR(4)    NOT NULL COMMENT '공통 코드', -- 공통 코드
	`CMMN_UPPER_CODE` VARCHAR(20)   NOT NULL COMMENT '공통상위코드', -- 공통상위코드
	`CMMN_CODE_NM`    VARCHAR(255)  NULL     COMMENT '공통 코드 이름', -- 공통 코드 이름
	`CMMN_CODE_DC`    VARCHAR(2048) NULL     COMMENT '공통 코드 설명', -- 공통 코드 설명
	`USE_AT`          VARCHAR(1)    NULL     COMMENT '사용 여부', -- 사용 여부
	`INQIRE_ORDR`     INT(11)       NULL     COMMENT '조회 순서' -- 조회 순서
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '공통코드상세';

-- 공통코드상세
ALTER TABLE `CMMN_CODE_DETAIL`
	ADD CONSTRAINT `PK_CMMN_CODE_DETAIL` -- 공통코드상세 기본키
		PRIMARY KEY (
			`GROUP_CODE`,      -- 그룹 코드
			`CMMN_CODE`,       -- 공통 코드
			`CMMN_UPPER_CODE`  -- 공통상위코드
		);

-- 공통코드상세
ALTER TABLE `CMMN_CODE_DETAIL`
	ADD CONSTRAINT `FK_CMMN_CODE_TO_CMMN_CODE_DETAIL` -- 공통코드 -> 공통코드상세
		FOREIGN KEY (
			`GROUP_CODE` -- 그룹 코드
		)
		REFERENCES `DQ_CMMN_CODE` ( -- 공통코드
			`GROUP_CODE` -- 그룹 코드
		);

-- 공통코드상세 데이터
INSERT INTO `CMMN_CODE_DETAIL` (`GROUP_CODE`,`CMMN_CODE`,`CMMN_UPPER_CODE`,`CMMN_CODE_NM`,`CMMN_CODE_DC`,`USE_AT`,`INQIRE_ORDR`) VALUES ('DQ_CODE','DQ_A','0','상세코드1','상세코드12','Y',1);
INSERT INTO `CMMN_CODE_DETAIL` (`GROUP_CODE`,`CMMN_CODE`,`CMMN_UPPER_CODE`,`CMMN_CODE_NM`,`CMMN_CODE_DC`,`USE_AT`,`INQIRE_ORDR`) VALUES ('DQ_CODE_A','DQ_B','0','상세코드2','상세코드2','Y',1);










-- 메뉴그룹관리
CREATE TABLE `MENU_GROUP` (
	`MENU_GROUP_SN` INT(11)      NOT NULL COMMENT '메뉴 그룹 일련번호', -- 메뉴 그룹 일련번호
	`MENU_GROUP_NM` VARCHAR(300) NULL     COMMENT '메뉴 그룹 명', -- 메뉴 그룹 명
	`USE_AT`        VARCHAR(1)   NULL     COMMENT '사용 여부' -- 사용 여부
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '메뉴그룹관리';

-- 메뉴그룹관리
ALTER TABLE `MENU_GROUP`
	ADD CONSTRAINT `PK_MENU_GROUP` -- 메뉴그룹관리 기본키
		PRIMARY KEY (
			`MENU_GROUP_SN` -- 메뉴 그룹 일련번호
		);

-- 메뉴그룹관리 데이터
INSERT INTO `MENU_GROUP` (`MENU_GROUP_SN`,`MENU_GROUP_NM`,`USE_AT`) VALUES (1,'PROPERTIES','Y');
INSERT INTO `MENU_GROUP` (`MENU_GROUP_SN`,`MENU_GROUP_NM`,`USE_AT`) VALUES (2,'BASIC','Y');
INSERT INTO `MENU_GROUP` (`MENU_GROUP_SN`,`MENU_GROUP_NM`,`USE_AT`) VALUES (3,'RULE','Y');
INSERT INTO `MENU_GROUP` (`MENU_GROUP_SN`,`MENU_GROUP_NM`,`USE_AT`) VALUES (4,'PROFILING','Y');









-- 메뉴관리
CREATE TABLE `MENU_MANAGE` (
	`MENU_SN`       INT(11)      NOT NULL COMMENT '메뉴 일련번호', -- 메뉴 일련번호
	`MENU_GROUP_SN` INT(11)      NOT NULL COMMENT '메뉴 그룹 일련번호', -- 메뉴 그룹 일련번호
	`MENU_DP_NO`    INT(11)      NULL     COMMENT '메뉴 깊이 넘버', -- 메뉴 깊이 넘버
	`INQIRE_ORDR`   INT(11)      NULL     COMMENT '조회 순서', -- 조회 순서
	`MENU_NM`       VARCHAR(300) NULL     COMMENT '메뉴 이름', -- 메뉴 이름
	`MENU_URL`     VARCHAR(600) NULL     COMMENT '메뉴 URL', -- 메뉴 URL
	`USE_AT`        VARCHAR(1)   NULL     COMMENT '사용 여부', -- 사용 여부
	`UPPER_MENU_SN` INT(11)      NULL     COMMENT '상위 메뉴 순번', -- 상위 메뉴 순번
	`MENU_ICON`     VARCHAR(100) NULL     COMMENT '메뉴 아이콘' -- 메뉴 아이콘
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '메뉴관리';

-- 메뉴관리
ALTER TABLE `MENU_MANAGE`
	ADD CONSTRAINT `PK_MENU_MANAGE` -- 메뉴관리 기본키
		PRIMARY KEY (
			`MENU_SN`,       -- 메뉴 일련번호
			`MENU_GROUP_SN`  -- 메뉴 그룹 일련번호
		);
		
-- 메뉴관리
ALTER TABLE `MENU_MANAGE`
	ADD CONSTRAINT `FK_MENU_GROUP_TO_MENU_MANAGE` -- 메뉴그룹관리 -> 메뉴관리
		FOREIGN KEY (
			`MENU_GROUP_SN` -- 메뉴 그룹 일련번호
		)
		REFERENCES `MENU_GROUP` ( -- 메뉴그룹관리
			`MENU_GROUP_SN` -- 메뉴 그룹 일련번호
		);

-- 메뉴관리 데이터
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (1,0,1,1,'최상위','/mngr/main','Y',0,NULL);
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (2,1,1,1,'공통정보','#','Y',0,'fa-info-circle');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (3,1,1,2,'사용자정보','/mngr/cmmnMng/cmmnUser','Y',0,'fa-users');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (4,1,1,3,'운영정보','#','Y',0,'fa-info-circle');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (5,2,1,1,'기본정보','#','Y',0,'fa-info-circle');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (6,2,1,1,'데이터연결','#','Y',0,'fa-database');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (7,3,1,1,'업무규칙관리','#','Y',0,'fa-cog');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (8,3,2,1,'허용 값 범위 설정','#','Y',7,NULL);
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (9,3,2,1,'사용자정의(정규식)','#','Y',7,NULL);
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (10,3,2,1,'사용자정의(SQL)','#','Y',7,NULL);
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (11,3,1,2,'패턴/지표 관리','#','Y',0,'fa-cog');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (12,4,1,1,'스키마 구조 분석','#','Y',0,'fa-cog');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (13,4,2,1,'테이블 구조 분석','#','Y',12,NULL);
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (14,4,2,1,'컬럼 구조 분석','#','Y',12,NULL);
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (15,4,1,2,'프로파일링 분석','#','Y',0,'fa-cog');
-- [삭제] INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (18,1,2,2,'메뉴권한','/mngr/menuMng/menuAuthor','Y',2,'');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (16,4,1,3,'프로파일링 결과','#','Y',0,'fa-cog');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (19,1,2,3,'공통코드관리','/mngr/cmmnMng/cmmnCode','Y',2,'fa-code');
INSERT INTO `MENU_MANAGE` (`MENU_SN`,`MENU_GROUP_SN`,`MENU_DP_NO`,`INQIRE_ORDR`,`MENU_NM`,`MENU_URL`,`USE_AT`,`UPPER_MENU_SN`,`MENU_ICON`) VALUES (17,1,2,1,'메뉴관리','/mngr/menuMng/menuManage','Y',2,'');







/*
-- 메뉴권한코드 [삭제]
CREATE TABLE `MENU_AUTHOR` (
	`MENU_SN`       INT(11)     NOT NULL COMMENT '메뉴 일련번호', -- 메뉴 일련번호
	`AUTHOR_CODE`   VARCHAR(20) NOT NULL COMMENT '권한 코드', -- 권한 코드
	`USE_AT`        VARCHAR(1)   NULL DEFAULT 'Y' COMMENT '사용 여부' -- 사용 여부
)
collate = `utf8_general_ci` ENGINE = InnoDB 
COMMENT '메뉴권한코드';

-- 메뉴권한코드 [삭제]
ALTER TABLE `MENU_AUTHOR`
	ADD CONSTRAINT `PK_MENU_AUTHOR` -- 메뉴권한코드 기본키
		PRIMARY KEY (
			`MENU_SN`,       -- 메뉴 일련번호
			`AUTHOR_CODE`  -- 권한 코드
			
		);
-- 메뉴권한코드 [삭제]
ALTER TABLE `MENU_AUTHOR`
	ADD CONSTRAINT `FK_MENU_MANAGE_TO_MENU_AUTHOR` -- 메뉴관리 -> 메뉴권한코드
		FOREIGN KEY (
			`MENU_SN`,       -- 메뉴 일련번호
			`MENU_GROUP_SN`  -- 메뉴 그룹 일련번호
		)
		REFERENCES `MENU_MANAGE` ( -- 메뉴관리
			`MENU_SN`,       -- 메뉴 일련번호
			`MENU_GROUP_SN`  -- 메뉴 그룹 일련번호
		);

-- 메뉴권한코드 데이터 [삭제]
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (2,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (3,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (4,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (5,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (6,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (7,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (8,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (9,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (10,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (11,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (12,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (13,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (14,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (15,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (16,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (17,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (18,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (19,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (20,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (21,'ROLE_ADMIN','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (2,'ROLE_USER','N');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (3,'ROLE_USER','N');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (4,'ROLE_USER','N');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (5,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (6,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (7,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (8,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (9,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (10,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (11,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (12,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (13,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (14,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (15,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (16,'ROLE_USER','Y');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (17,'ROLE_USER','N');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (18,'ROLE_USER','N');
INSERT INTO `MENU_AUTHOR` (`MENU_SN`,`AUTHOR_CODE`,`USE_AT`) VALUES (19,'ROLE_USER','N');

*/