CREATE TABLE `SCHEDULER` (
  `INSTT_CODE` char(7) NOT NULL COMMENT '기관 코드',
  `DGNSS_SAVE_ID` varchar(20) NOT NULL COMMENT '분석설정저장아이디',
  `DGNSS_DBMS_ID` char(4) NOT NULL COMMENT '진단대상데이터베이순버',
  `SCHEDULE_ID` char(4) NOT NULL COMMENT '스케줄러아이디',
  `SCHEDULE_NM` varchar(20) DEFAULT NULL COMMENT '스케줄러 이름',
  `SCHEDULE_DE` varchar(8) COMMENT '스케줄 시간',
  `USE_AT` char(1) DEFAULT NULL COMMENT '사용여부',
  `REGIST_DT` datetime DEFAULT NULL COMMENT '등록 일시',
  PRIMARY KEY (`INSTT_CODE`,`DGNSS_SAVE_ID`,`DGNSS_DBMS_ID`,`SCHEDULE_ID`),
  KEY `FK_DGNSS_SAVE_TO_SCHEDULER` (`DGNSS_DBMS_ID`,`INSTT_CODE`,`DGNSS_SAVE_ID`),
  CONSTRAINT `FK_DGNSS_SAVE_TO_SCHEDULER` FOREIGN KEY (`DGNSS_DBMS_ID`, `INSTT_CODE`,`DGNSS_SAVE_ID`) REFERENCES `DGNSS_SAVE` (`DGNSS_DBMS_ID`, `INSTT_CODE`,`DGNSS_SAVE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='스케줄러';
